[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rlbot"
dynamic = ["version"]
requires-python = ">= 3.11"
dependencies = [
    "flatbuffers==23.5.26",
    "psutil==5.*",
    "docopt==0.6.*"
]

[tool.setuptools.dynamic]
version = {attr = "rlbot.__version__"}
