# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flat

class GameStateType(object):
    # Game has not been created yet
    Inactive = 0
    # 3-2-1 countdown
    Countdown = 1
    # After countdown, but before ball has been hit
    Kickoff = 2
    # Ball has been hit
    Active = 3
    # A goal was scored. Waiting for replay.
    GoalScored = 4
    # Watching replay
    Replay = 5
    # Game paused
    Paused = 6
    # Match has ended
    Ended = 7
