# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flat

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Rocket League is notifying us that some player has moved their controller. This is an *output*
class PlayerInputChange(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PlayerInputChange()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPlayerInputChange(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PlayerInputChange
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PlayerInputChange
    def PlayerIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # PlayerInputChange
    def ControllerState(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from rlbot.flat.ControllerState import ControllerState
            obj = ControllerState()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PlayerInputChange
    def DodgeForward(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # PlayerInputChange
    def DodgeRight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def PlayerInputChangeStart(builder):
    builder.StartObject(4)

def Start(builder):
    PlayerInputChangeStart(builder)

def PlayerInputChangeAddPlayerIndex(builder, playerIndex):
    builder.PrependInt32Slot(0, playerIndex, 0)

def AddPlayerIndex(builder, playerIndex):
    PlayerInputChangeAddPlayerIndex(builder, playerIndex)

def PlayerInputChangeAddControllerState(builder, controllerState):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(controllerState), 0)

def AddControllerState(builder, controllerState):
    PlayerInputChangeAddControllerState(builder, controllerState)

def PlayerInputChangeAddDodgeForward(builder, dodgeForward):
    builder.PrependFloat32Slot(2, dodgeForward, 0.0)

def AddDodgeForward(builder, dodgeForward):
    PlayerInputChangeAddDodgeForward(builder, dodgeForward)

def PlayerInputChangeAddDodgeRight(builder, dodgeRight):
    builder.PrependFloat32Slot(3, dodgeRight, 0.0)

def AddDodgeRight(builder, dodgeRight):
    PlayerInputChangeAddDodgeRight(builder, dodgeRight)

def PlayerInputChangeEnd(builder):
    return builder.EndObject()

def End(builder):
    return PlayerInputChangeEnd(builder)

import rlbot.flat.ControllerState
try:
    from typing import Optional
except:
    pass

class PlayerInputChangeT(object):

    # PlayerInputChangeT
    def __init__(self):
        self.playerIndex = 0  # type: int
        self.controllerState = None  # type: Optional[rlbot.flat.ControllerState.ControllerStateT]
        self.dodgeForward = 0.0  # type: float
        self.dodgeRight = 0.0  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        playerInputChange = PlayerInputChange()
        playerInputChange.Init(buf, pos)
        return cls.InitFromObj(playerInputChange)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, playerInputChange):
        x = PlayerInputChangeT()
        x._UnPack(playerInputChange)
        return x

    # PlayerInputChangeT
    def _UnPack(self, playerInputChange):
        if playerInputChange is None:
            return
        self.playerIndex = playerInputChange.PlayerIndex()
        if playerInputChange.ControllerState() is not None:
            self.controllerState = rlbot.flat.ControllerState.ControllerStateT.InitFromObj(playerInputChange.ControllerState())
        self.dodgeForward = playerInputChange.DodgeForward()
        self.dodgeRight = playerInputChange.DodgeRight()

    # PlayerInputChangeT
    def Pack(self, builder):
        if self.controllerState is not None:
            controllerState = self.controllerState.Pack(builder)
        PlayerInputChangeStart(builder)
        PlayerInputChangeAddPlayerIndex(builder, self.playerIndex)
        if self.controllerState is not None:
            PlayerInputChangeAddControllerState(builder, controllerState)
        PlayerInputChangeAddDodgeForward(builder, self.dodgeForward)
        PlayerInputChangeAddDodgeRight(builder, self.dodgeRight)
        playerInputChange = PlayerInputChangeEnd(builder)
        return playerInputChange
