# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flat

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# A bot controlled by the RLBot framework
class RLBotPlayer(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RLBotPlayer()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRLBotPlayer(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RLBotPlayer
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def RLBotPlayerStart(builder):
    builder.StartObject(0)

def Start(builder):
    RLBotPlayerStart(builder)

def RLBotPlayerEnd(builder):
    return builder.EndObject()

def End(builder):
    return RLBotPlayerEnd(builder)


class RLBotPlayerT(object):

    # RLBotPlayerT
    def __init__(self):
        pass

    @classmethod
    def InitFromBuf(cls, buf, pos):
        rlbotPlayer = RLBotPlayer()
        rlbotPlayer.Init(buf, pos)
        return cls.InitFromObj(rlbotPlayer)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, rlbotPlayer):
        x = RLBotPlayerT()
        x._UnPack(rlbotPlayer)
        return x

    # RLBotPlayerT
    def _UnPack(self, rlbotPlayer):
        if rlbotPlayer is None:
            return

    # RLBotPlayerT
    def Pack(self, builder):
        RLBotPlayerStart(builder)
        rlbotPlayer = RLBotPlayerEnd(builder)
        return rlbotPlayer
